name: Stookwijzer Twice Daily

on:
  schedule:
    # 10:00 UTC == 12:00 NL, 18:00 UTC == 20:00 NL
    - cron: '0 10,18 * * *'

jobs:
  run_stookwijzer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pytz pandas

      - name: Run script and append output
        run: python stookwijzer.py

      - name: Commit new data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stookwijzer_output.csv
          git commit -m "Update stookwijzer_output.csv [auto]" || echo "No changes to commit"
          git push
